### ISSUE TITLE
[Bug]: jdk8版本无法兼容jdk17，由于Redisson

### ISSUE THREAD

**Issue by jackmomos** [twelvet-s/twelvet#31]
### twelvet Version

2.7.18

### Node Version

v16

### JDK Version

JDK17

### Does it still exist

It can be reproduced.

### Bug Description

Redisson在JDK17版本下无法启动，缺失
java.lang.NoClassDefFoundError: org/springframework/data/redis/connection/RedisZSetCommands$Tuple

**Comment by twelvet-s** [comment]
已修复，具体版本适配https://github.com/redisson/redisson/issues/4675
